INSERT INTO "MY_USER" ("ID", "NAME", "SUR_NAME") VALUES (1, 'test1', 'ASD1');
INSERT INTO "MY_USER" ("ID", "NAME", "SUR_NAME") VALUES (2, 'test2', 'ASD2');
INSERT INTO "MY_USER" ("ID", "NAME", "SUR_NAME") VALUES (3, 'test3', 'ASD3');
